nameOverride: ""
fullnameOverride: ""
kubeVersion: ""

replicaCount: 1

image:
  registry: example.registry.com:5678
  pullPolicy: Always
  repository: tinode/tinode
  tag: 0.20.0

imagePullSecrets:
  - name: "pullSecret-registry"

cloudIngress: "k8s-cloud.example.com"

# Default listen on 0.0.0.0:6060
listenAddress: ""
listenPort: 6060

# Use adapter depends on your database (see supported adapters)
storeUseAdapter: "mongodb"

extraEnvVars:
  - name: MONGODB_ADDRESS
    value: "192.168.0.1:5050"
  - name: MONGODB_DB
    value: "tinode"
  - name: MONGODB_SKIP_TLS_VERIFY
    value: 'true'
  - name: MONGODB_TLS_ENABLED
    value: 'false'

smtpConfigurationEnv:
  # Set empty to disable email validation.
  EMAIL_VERIFICATION_REQUIRED: "auth"
  # Address of the SMPT server to use.
  SMTP_SERVER: "smtp.example.com"
  # SMTP port to use. "25" for basic email RFC 5321 (2821, 821), "587" for RFC 3207 (TLS).
  SMTP_PORT: "25"
  # Optional login to use for authentication; if missing, the connection is not authenticated.
  SMTP_LOGIN: ""
  #  RFC 5322 email address to show in the From: field.
  SMTP_SENDER: "noreply@example.com"
  # Missing or empty list means any email domain is accepted.
  SMTP_DOMAINS: ""
  # Dummy response to accept. REMOVE IT IN PRODUCTION!!! Otherwise anyone will be able to register
  DEBUG_EMAIL_VERIFICATION_CODE: ""

secrets:
  MONGODB_USERNAME: ""
  MONGODB_PASSWORD: ""
# Password to use when authenticating the sender; used only if "login" is provided.
  SMTP_PASSWORD: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 1
    memory: 500Mi
  requests:
    cpu: 200m
    memory: 500Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector:
      kubernetes.io/role: worker

tolerations: []

affinity: {}

configuration: ""