apiVersion: v1
kind: Service
metadata:
  name: {{ include "tinode.fullname" . }}
  labels:
    {{- include "tinode.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.listenPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "tinode.selectorLabels" . | nindent 4 }}
